# Generated by Django 3.2 on 2023-03-14 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='Email', max_length=50)),
                ('factor', models.CharField(default='None', max_length=50)),
                ('mailsent', models.CharField(default='No', max_length=10)),
            ],
        ),
    ]
